/*
 * Copyright 2026 Francesco Bilotta
 * Licensed under the Apache License, Version 2.0 (the "License").
 */
package dev.lievit.compiler.convert;

import java.util.Set;

/**
 * Renders a neutral {@link ViewNode} tree to a JTE template body, the backward half of the SFC-&gt;MFC
 * convert (issue #141, ADR-0071). It is the exact inverse of {@link JteViewParser}: an
 * {@link ViewNode.Element} renders as an indented start/close tag (self-closing for a void element),
 * a {@link ViewNode.Literal} as text, an {@link ViewNode.Expression} as {@code ${expr}}, a
 * {@link ViewNode.Raw} as {@code $unsafe{markup}}, a literal attribute verbatim, a dynamic attribute
 * as {@code name="${expr}"}, and a boolean attribute bare.
 *
 * <p>It emits only the markup body; the {@code @param} header is generated by the convert command
 * from the component's {@code @Wire} fields (so the two shapes cannot drift), not carried in the AST.
 * The indentation is two-space, deterministic, and round-trip stable (the parser collapses
 * insignificant whitespace, so re-parsing the written body yields the same AST). Pure Java, zero
 * Spring.
 */
public final class JteViewWriter {

    private static final Set<String> VOID_ELEMENTS =
            Set.of(
                    "area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta",
                    "param", "source", "track", "wbr");

    private static final String INDENT = "    ";

    /**
     * Renders a view node to a JTE template body (no header).
     *
     * @param node the neutral view node (the component's single root)
     * @return the JTE body markup, newline-terminated
     */
    public String write(ViewNode node) {
        StringBuilder out = new StringBuilder();
        writeNode(node, out, 0);
        return out.toString();
    }

    private void writeNode(ViewNode node, StringBuilder out, int depth) {
        switch (node) {
            case ViewNode.Element element -> writeElement(element, out, depth);
            case ViewNode.Literal literal -> out.append(INDENT.repeat(depth)).append(literal.value()).append('\n');
            case ViewNode.Expression expression -> out.append(INDENT.repeat(depth)).append("${").append(expression.expression()).append("}\n");
            case ViewNode.Raw raw -> out.append(INDENT.repeat(depth)).append("$unsafe{").append(raw.markup()).append("}\n");
        }
    }

    private void writeElement(ViewNode.Element element, StringBuilder out, int depth) {
        String pad = INDENT.repeat(depth);
        out.append(pad).append('<').append(element.tag());
        for (ViewAttribute attr : element.attributes()) {
            writeAttribute(attr, out);
        }
        if (VOID_ELEMENTS.contains(element.tag())) {
            out.append(">\n");
            return;
        }
        // Inline a single text/expression child on the same line (the common <span>${count}</span> case).
        if (element.children().size() == 1 && !(element.children().get(0) instanceof ViewNode.Element)) {
            out.append('>').append(inline(element.children().get(0))).append("</").append(element.tag()).append(">\n");
            return;
        }
        if (element.children().isEmpty()) {
            out.append("></").append(element.tag()).append(">\n");
            return;
        }
        out.append(">\n");
        for (ViewNode child : element.children()) {
            writeNode(child, out, depth + 1);
        }
        out.append(pad).append("</").append(element.tag()).append(">\n");
    }

    private static String inline(ViewNode node) {
        return switch (node) {
            case ViewNode.Literal literal -> literal.value();
            case ViewNode.Expression expression -> "${" + expression.expression() + "}";
            case ViewNode.Raw raw -> "$unsafe{" + raw.markup() + "}";
            case ViewNode.Element ignored -> ""; // unreachable: guarded by the caller
        };
    }

    private void writeAttribute(ViewAttribute attr, StringBuilder out) {
        out.append(' ').append(attr.name());
        if (attr.value().isEmpty()) {
            return;
        }
        if (attr.dynamic()) {
            out.append("=\"${").append(attr.value().orElseThrow()).append("}\"");
        } else {
            out.append("=\"").append(attr.value().orElseThrow()).append('"');
        }
    }
}
